# Generated by Django 2.0 on 2019-07-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_status', models.CharField(default='空闲中', max_length=20)),
                ('waiting_number', models.IntegerField(default=0)),
                ('fk_doctor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_two_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_two_outer_time', models.DateTimeField(auto_now_add=True)),
                ('continue_live_day', models.CharField(default=None, max_length=200)),
                ('patient_one_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientOne')),
            ],
        ),
    ]
