# Generated by Django 2.0 on 2019-07-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_outside', models.CharField(max_length=10)),
                ('depart_heart', models.CharField(max_length=10)),
                ('depart_rapid', models.CharField(max_length=10)),
                ('depart_bone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=11)),
                ('user_password', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(max_length=10)),
                ('user_card', models.CharField(max_length=18)),
                ('user_age', models.CharField(max_length=3)),
                ('user_gender', models.CharField(max_length=2)),
                ('user_level', models.CharField(max_length=10)),
                ('user_phone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='fk_doctor_message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.UserInfo'),
        ),
    ]
