# Generated by Django 2.1.7 on 2019-07-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_house', '0002_auto_20190715_2005'),
        ('registration', '0002_auto_20190715_2005'),
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormessage',
            name='doctor_belong',
        ),
        migrations.RemoveField(
            model_name='doctormessage',
            name='fk_doctor_message_user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DoctorMessage',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
