# Generated by Django 2.1.2 on 2019-08-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_status', models.CharField(default='空闲中', max_length=20)),
                ('waiting_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_belong', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Main_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediacal_redord_NO', models.IntegerField(default=0)),
                ('patient_name', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=10)),
                ('drug_name', models.CharField(max_length=30)),
                ('drug_number', models.IntegerField(default=0)),
                ('drug_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=20)),
                ('medicine_number', models.IntegerField()),
                ('medicine_outer_price', models.FloatField()),
                ('medicine_enter_price', models.FloatField()),
                ('medicine_message', models.CharField(max_length=200)),
                ('fk_medicine_type_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_one_name', models.CharField(max_length=20)),
                ('medicine_one_number', models.IntegerField()),
                ('medicine_one_outer_price', models.FloatField()),
                ('medicine_one_yes_no', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default=0)),
                ('source', models.CharField(max_length=200)),
                ('collect_money', models.FloatField(default=0)),
                ('collect_time', models.DateTimeField()),
                ('is_hospital', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=6)),
                ('patient_age', models.IntegerField()),
                ('patient_sex', models.CharField(max_length=50)),
                ('patient_phone', models.CharField(max_length=11)),
                ('patient_card', models.CharField(max_length=18)),
                ('patient_status', models.CharField(max_length=200)),
                ('patient_history', models.CharField(default=None, max_length=600)),
                ('patient_registed_time', models.DateTimeField(auto_now=True)),
                ('patient_is_live', models.CharField(default=None, max_length=200, null=True)),
                ('patient_live_day', models.CharField(default=None, max_length=300, null=True)),
                ('patient_condition', models.CharField(default=None, max_length=600, null=True)),
                ('patient_message', models.CharField(default=None, max_length=600, null=True)),
                ('patient_one_enter_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient_one_outer_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient_over_look_doctor', models.CharField(default=0, max_length=20, null=True)),
                ('patient_take_medicine_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('fk_patient_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Department')),
                ('fk_patient_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_two_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_two_outer_time', models.DateTimeField(auto_now_add=True)),
                ('continue_live_day', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(default=0, max_length=11)),
                ('user_password', models.CharField(default=0, max_length=10)),
                ('user_name', models.CharField(default=0, max_length=20)),
                ('user_email', models.EmailField(default=0, max_length=254)),
                ('user_card', models.CharField(default=0, max_length=18)),
                ('user_age', models.CharField(default=0, max_length=3)),
                ('user_gender', models.CharField(default='男', max_length=2)),
                ('user_level', models.CharField(default=0, max_length=10)),
                ('user_phone', models.CharField(default=0, max_length=16)),
                ('user_status', models.CharField(default='禁用', max_length=20)),
                ('doctor_belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Department')),
                ('user_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Role')),
            ],
        ),
        migrations.AddField(
            model_name='money',
            name='fk_patientone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.PatientOne'),
        ),
        migrations.AddField(
            model_name='medicine_one',
            name='fk_patient_medicine_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.PatientOne'),
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='fk_doctor_message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.UserInfo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fk_doctor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.UserInfo'),
        ),
    ]
