# Generated by Django 2.1.2 on 2019-07-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_outside', models.CharField(max_length=10)),
                ('depart_heart', models.CharField(max_length=10)),
                ('depart_rapid', models.CharField(max_length=10)),
                ('depart_bone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_status', models.CharField(default='空闲中', max_length=20)),
                ('waiting_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_belong', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=6)),
                ('patient_card', models.CharField(max_length=18)),
                ('patient_status', models.CharField(max_length=200)),
                ('patient_main_doctor', models.CharField(max_length=10)),
                ('patient_medicine', models.CharField(default=None, max_length=200)),
                ('patient_is_live', models.CharField(default=None, max_length=200)),
                ('patient_live_day', models.CharField(default=None, max_length=200)),
                ('patient_condition', models.CharField(default=None, max_length=200)),
                ('patient_history', models.CharField(default=None, max_length=200)),
                ('patient_message', models.CharField(default=None, max_length=200)),
                ('patient_one_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_one_outer_time', models.DateTimeField(auto_now_add=True)),
                ('patient_take_medicine_time', models.DateTimeField(auto_now_add=True)),
                ('fk_patient_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_two_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_two_outer_time', models.DateTimeField(auto_now_add=True)),
                ('continue_live_day', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=11)),
                ('user_password', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(max_length=10)),
                ('user_card', models.CharField(max_length=18)),
                ('user_age', models.CharField(max_length=3)),
                ('user_gender', models.CharField(max_length=2)),
                ('user_level', models.CharField(max_length=10)),
                ('user_phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='fk_medicine_type_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Department'),
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='fk_doctor_message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.UserInfo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fk_doctor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.UserInfo'),
        ),
    ]
