# Generated by Django 2.1.7 on 2019-07-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='fk_medicine_type_department',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
