# Generated by Django 2.1.2 on 2019-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_house', '0002_auto_20190715_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='depart_bone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='depart_heart',
        ),
        migrations.RemoveField(
            model_name='department',
            name='depart_rapid',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(max_length=200),
        ),
    ]
