# Generated by Django 2.1.2 on 2019-07-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_house', '0003_auto_20190716_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50)),
                ('dcotor', models.CharField(max_length=50)),
                ('pay_money', models.CharField(max_length=50)),
                ('medicine_house', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='depart_outside',
            new_name='depart_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='doctor_belong',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_house.Role'),
        ),
    ]
