# Generated by Django 2.0 on 2019-07-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=6)),
                ('patient_card', models.CharField(max_length=18)),
                ('patient_status', models.CharField(max_length=200)),
                ('patient_main_doctor', models.CharField(max_length=10)),
                ('patient_medicine', models.CharField(default=None, max_length=20)),
                ('patient_is_live', models.CharField(default=None, max_length=20)),
                ('patient_live_day', models.CharField(default=None, max_length=20)),
                ('patient_condition', models.CharField(default=None, max_length=200)),
                ('patient_history', models.CharField(default=None, max_length=200)),
                ('patient_message', models.CharField(default=None, max_length=200)),
                ('patient_one_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_one_outer_time', models.DateTimeField(auto_now_add=True)),
                ('patient_take_medicine_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
