# Generated by Django 2.1.2 on 2019-07-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190715_1952'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientOne',
        ),
    ]
