# Generated by Django 2.1.7 on 2019-07-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_outside', models.CharField(max_length=10)),
                ('depart_heart', models.CharField(max_length=10)),
                ('depart_rapid', models.CharField(max_length=10)),
                ('depart_bone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_status', models.CharField(default='空闲中', max_length=20)),
                ('waiting_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_belong', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=20)),
                ('medicine_number', models.IntegerField()),
                ('medicine_outer_price', models.FloatField()),
                ('medicine_enter_price', models.FloatField()),
                ('medicine_message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_one_name', models.CharField(max_length=20)),
                ('medicine_one_number', models.IntegerField()),
                ('medicine_one_outer_price', models.FloatField()),
                ('medicine_one_hospitalized', models.CharField(default=0, max_length=20)),
                ('medicine_one_numbers_days1', models.IntegerField(default=0)),
                ('medicine_one_time', models.DateTimeField(auto_now_add=True)),
                ('medicine_one_twotime', models.DateTimeField(auto_now=True)),
                ('medicine_one_numbers_twodays', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_two_enter_time', models.DateTimeField(auto_now_add=True)),
                ('patient_two_outer_time', models.DateTimeField(auto_now_add=True)),
                ('continue_live_day', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=11)),
                ('user_password', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(max_length=10)),
                ('user_card', models.CharField(max_length=18)),
                ('user_age', models.CharField(max_length=3)),
                ('user_gender', models.CharField(max_length=2)),
                ('user_level', models.CharField(max_length=10)),
                ('user_phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='patientone',
            name='patient_condition',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='patientone',
            name='patient_history',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='patientone',
            name='patient_is_live',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='patientone',
            name='patient_live_day',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='patientone',
            name='patient_message',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='medicine_one',
            name='fk_patient_medicine_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientOne'),
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='fk_doctor_message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.UserInfo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fk_doctor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.UserInfo'),
        ),
    ]
