# Generated by Django 2.1.7 on 2019-07-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190720_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_one',
            name='medicine_one_hospitalized',
        ),
        migrations.RemoveField(
            model_name='medicine_one',
            name='medicine_one_numbers_days1',
        ),
        migrations.RemoveField(
            model_name='medicine_one',
            name='medicine_one_numbers_twodays',
        ),
        migrations.RemoveField(
            model_name='medicine_one',
            name='medicine_one_time',
        ),
        migrations.RemoveField(
            model_name='medicine_one',
            name='medicine_one_twotime',
        ),
    ]
