# Generated by Django 2.1.7 on 2019-07-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190720_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientone',
            name='patient_over_look_doctor',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
