# Generated by Django 2.1.7 on 2019-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_patientone_patient_over_look_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_one',
            name='medicine_one_yes_no',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
